- fog-openstack.gemspec
- spec/spec_helper.rb
> Coveralls support

- gemfiles/Gemfile-1.9
- tests/helper.rb
Add coveralls init to the right helper
> Add coveralls init to the right helper

- .travis.yml
> Notifications for gitter

- .hound.yml
Defining our rubocop.yml for houndci
> Defining our rubocop.yml for houndci

- README.md
Because people need to know how this thing works!
Looking to get this cross-referenced with the [OpenStack AppDev](https://www.openstack.org/appdev/) initiative so that their documentation on how to work with OpenStack via Ruby matches up neatly with the documentation here in the README.
> Usage documentation.

- lib/fog/openstack/network.rb
- lib/fog/openstack/requests/network/get_network.rb
Pull request from: https://github.com/fog/fog/pull/3846
> return network in mock data in stead of creating a new one

- lib/fog/openstack.rb
Hello,
This fix resolve all our problem explain in these issue : https://github.com/fog/fog-openstack/issues/59 and https://github.com/fog/fog-core/issues/178 .
I'm not sure it is the best response at the problem, but for us it works and i think it can help.
> fix bug mock reset

- lib/fog/openstack/models/network/floating_ip.rb
- tests/openstack/models/network/floating_ip_tests.rb
new PR from #63
* added associate and disassociate into floating_ip objet
> Rework floating ip

- lib/fog/openstack/network.rb
> Fix path setting on reauthentication

- fog-openstack.gemspec
- lib/fog/openstack.rb
- lib/fog/openstack/docs/introspection.md
- lib/fog/openstack/examples/introspection/basics.rb
- lib/fog/openstack/introspection.rb
- lib/fog/openstack/requests/introspection/abort_introspection.rb
- lib/fog/openstack/requests/introspection/create_introspection.rb
- lib/fog/openstack/requests/introspection/create_rules.rb
- lib/fog/openstack/requests/introspection/delete_rules.rb
- lib/fog/openstack/requests/introspection/delete_rules_all.rb
- lib/fog/openstack/requests/introspection/get_introspection.rb
- lib/fog/openstack/requests/introspection/get_introspection_details.rb
- lib/fog/openstack/requests/introspection/get_rules.rb
- lib/fog/openstack/requests/introspection/list_rules.rb
- tests/fixtures/introspection.yaml
- tests/openstack/requests/introspection/introspection_tests.rb
- tests/openstack/requests/introspection/rules_tests.rb
Requests for introspection and rules
No Models yet
Note: Requires fog-core => 1.37.0 (Mostly for Mock tests)
> Add introspection service

- lib/fog/openstack/introspection.rb
- lib/fog/openstack/models/introspection/rules.rb
- lib/fog/openstack/models/introspection/rules_collection.rb
Models and Collection for Introspection Rules
> Add introspection models

- fog-openstack.gemspec
> Move fog-core dependency

- lib/fog/openstack.rb
- lib/fog/openstack/core.rb
- lib/fog/openstack/identity_v3.rb
- lib/fog/openstack/models/identity_v3/projects.rb
Make caching for keystone v3 optional and configurable
Fixes GH issue:
https://github.com/fog/fog-openstack/issues/56
> Make caching for keystone v3 optional and configurable

- lib/fog/openstack/image_v1.rb
- lib/fog/openstack/image_v2.rb
- lib/fog/openstack/models/image_v2/image.rb
- spec/fixtures/openstack/image_v1/common_setup.yml
- spec/fixtures/openstack/image_v1/list_images.yml
- spec/fixtures/openstack/image_v2/common_setup.yml
- spec/fixtures/openstack/image_v2/image_v2_activation.yml
- spec/fixtures/openstack/image_v2/image_v2_create_id.yml
- spec/fixtures/openstack/image_v2/image_v2_crud.yml
- spec/fixtures/openstack/image_v2/image_v2_member_crudl.yml
- spec/fixtures/openstack/image_v2/image_v2_tags.yml
- spec/fixtures/openstack/image_v2/image_v2_upload_download.yml
- spec/image_v2_spec.rb
Support getting custom image properties from model
Don't add version to path
Add dummy class for RSpec 'describe' reference
> Image API fixes

- lib/fog/openstack/models/network/floating_ip.rb
- lib/fog/openstack/network.rb
- spec/fog/network/get_service_with_token.yml
- spec/fog/network_api_path/common_setup.yml
- spec/fog/network_api_path/get_service_with_token.yml
- spec/fog/network_api_path/subnets_crud.yml
Add router_id attribute
Use get_supported_version_path instead of get_supported_version when setting API path
> Network API fixes

- fog-openstack.gemspec
- lib/fog/openstack.rb
- lib/fog/openstack/docs/nfv.md
- lib/fog/openstack/models/collection.rb
- lib/fog/openstack/models/nfv/vnf.rb
- lib/fog/openstack/models/nfv/vnfd.rb
- lib/fog/openstack/models/nfv/vnfds.rb
- lib/fog/openstack/models/nfv/vnfs.rb
- lib/fog/openstack/nfv.rb
- lib/fog/openstack/requests/nfv/create_vnf.rb
- lib/fog/openstack/requests/nfv/create_vnfd.rb
- lib/fog/openstack/requests/nfv/delete_vnf.rb
- lib/fog/openstack/requests/nfv/delete_vnfd.rb
- lib/fog/openstack/requests/nfv/get_vnf.rb
- lib/fog/openstack/requests/nfv/get_vnfd.rb
- lib/fog/openstack/requests/nfv/list_vnfds.rb
- lib/fog/openstack/requests/nfv/list_vnfs.rb
- lib/fog/openstack/requests/nfv/update_vnf.rb
- tests/openstack/models/nfv/vnf_tests.rb
- tests/openstack/models/nfv/vnfd_tests.rb
- tests/openstack/models/nfv/vnfds_tests.rb
- tests/openstack/models/nfv/vnfs_tests.rb
- tests/openstack/requests/nfv/vnf_tests.rb
- tests/openstack/requests/nfv/vnfd_tests.rb
Add NFV service requests and models. Adding also request and
models tests and documentation.
> Add NFV service

- lib/fog/openstack/docs/network.md
- lib/fog/openstack/examples/network/network_rbac.rb
as suggested in https://github.com/fog/fog-openstack/pull/108
@dhague, @gildub
> network doc and example

- Rakefile
- test/test_helper.rb
Addresses https://github.com/fog/fog-openstack/issues/140
by properly setting up fog mock environment.
> fixes ENV['FOG_MOCK']

- lib/fog/openstack/requests/compute/attach_volume.rb
- lib/fog/openstack/requests/compute/detach_volume.rb
Hi guys !
Just a little PR for updating volume's status when that was attached or detached.
Thanks
> Mock volume's status when attach and detach perform

- lib/fog/openstack/models/monitoring/alarms.rb
- lib/fog/openstack/requests/monitoring/get_alarm.rb
This fixes #155. 
Could you review @dhague ?
> fix monitoring get alarm by id

- lib/fog/openstack/models/orchestration/stack.rb
@Ladas @mdarby could you guys approve this PR as promised in #164 comment?
> keep the default_options for compatibility

- lib/fog/dns/openstack/v2.rb
- lib/fog/dns/openstack/v2/requests/create_recordset.rb
- lib/fog/dns/openstack/v2/requests/create_zone.rb
- lib/fog/dns/openstack/v2/requests/delete_recordset.rb
- lib/fog/dns/openstack/v2/requests/delete_zone.rb
- lib/fog/dns/openstack/v2/requests/get_recordset.rb
- lib/fog/dns/openstack/v2/requests/get_zone.rb
- lib/fog/dns/openstack/v2/requests/list_recordsets.rb
- lib/fog/dns/openstack/v2/requests/update_recordset.rb
- lib/fog/dns/openstack/v2/requests/update_zone.rb
- test/helpers/dns_v2_helper.rb
- test/requests/dns_v2/quota_tests.rb
- test/requests/dns_v2/recordset_tests.rb
- test/requests/dns_v2/zone_tests.rb
as promised some more dns v2 requests
> DNS V2 crud zone + recordsets

- lib/fog/compute/openstack/models/server.rb
> fallback for empty addresses

- lib/fog/network/openstack/requests/update_router.rb
> add routes option to router update to add extra routes

- lib/fog/network/openstack.rb
- lib/fog/network/openstack/requests/create_network.rb
- lib/fog/network/openstack/requests/update_network.rb
- test/requests/network/network_tests.rb
Adds port_security_enabled, qos_policy_id options to be created
and updated.
Allows router_external option to be updated.
Addresses https://github.com/fog/fog-openstack/issues/192
> Adds fields to requests network

- lib/fog/openstack.rb
Fix https://github.com/fog/fog-openstack/issues/183
Reordered the autoloaded by alphabetical order.
Note: Left planning to be done later
because its using a non consistent path and name.
> Replaces requires with autoload

- fog-openstack.gemspec
- gemfiles/Gemfile-1.9
- spec/spec_helper.rb
- test/test_helper.rb
Deactivates coveralls until following issue has been fixed
https://github.com/fog/fog-openstack/issues/202
> Workaround for coveralls dep issues

- lib/fog/network/openstack.rb
- lib/fog/network/openstack/models/extension.rb
- lib/fog/network/openstack/models/extensions.rb
- lib/fog/network/openstack/requests/get_extension.rb
- lib/fog/network/openstack/requests/list_extensions.rb
- test/requests/network/extension_tests.rb
Includes
Request: list_extensions, get_extension
Models: extension
Collection: extensions
Unit tests for above
Reference: https://github.com/fog/fog-openstack/issues/199
> Enhancement: adds neutron extensions

- lib/fog/network/openstack.rb
- lib/fog/network/openstack/models/security_group.rb
- lib/fog/network/openstack/requests/update_security_group.rb
- test/models/network/security_group_tests.rb
- test/requests/network/security_group_tests.rb
Adds update call to request and corresponding model
> Allows security_groups to update

- docs/common/connection_params.md
- docs/common/resources.md
- docs/compute.md
- docs/getting_started.md
- docs/network.md
- docs/orchestration.md
- docs/planning.md
- docs/storage.md
- docs/workflow.md
about connection_parameters and additional resources
moved out of #205
@gildub FYI
> consolidate common documentation

- docs/getting_started.md
- docs/shared_file_system.md
- examples/shared_file_system/basics.rb
- lib/fog/openstack.rb
- lib/fog/shared_file_system/openstack.rb
- lib/fog/shared_file_system/openstack/models/network.rb
- lib/fog/shared_file_system/openstack/models/networks.rb
- lib/fog/shared_file_system/openstack/models/share.rb
- lib/fog/shared_file_system/openstack/models/shares.rb
- lib/fog/shared_file_system/openstack/requests/create_share.rb
- lib/fog/shared_file_system/openstack/requests/create_share_network.rb
- lib/fog/shared_file_system/openstack/requests/delete_share.rb
- lib/fog/shared_file_system/openstack/requests/delete_share_network.rb
- lib/fog/shared_file_system/openstack/requests/get_share.rb
- lib/fog/shared_file_system/openstack/requests/get_share_network.rb
- lib/fog/shared_file_system/openstack/requests/list_share_networks.rb
- lib/fog/shared_file_system/openstack/requests/list_share_networks_detail.rb
- lib/fog/shared_file_system/openstack/requests/list_shares.rb
- lib/fog/shared_file_system/openstack/requests/list_shares_detail.rb
- lib/fog/shared_file_system/openstack/requests/update_share.rb
- lib/fog/shared_file_system/openstack/requests/update_share_network.rb
- spec/fixtures/openstack/shared_file_system/common_setup.yml
- spec/fixtures/openstack/shared_file_system/share_crud.yml
- spec/fixtures/openstack/shared_file_system/share_net_crud.yml
- spec/shared_context.rb
- spec/shared_file_system_spec.rb
Initial manila implementation.
I plan to add snapshots and quota soon.
> Manila Shares

- examples/shared_file_system/basics.rb
- lib/fog/shared_file_system/openstack.rb
- lib/fog/shared_file_system/openstack/models/share.rb
- lib/fog/shared_file_system/openstack/models/snapshot.rb
- lib/fog/shared_file_system/openstack/models/snapshots.rb
- lib/fog/shared_file_system/openstack/requests/create_snapshot.rb
- lib/fog/shared_file_system/openstack/requests/delete_snapshot.rb
- lib/fog/shared_file_system/openstack/requests/get_snapshot.rb
- lib/fog/shared_file_system/openstack/requests/list_snapshots.rb
- lib/fog/shared_file_system/openstack/requests/list_snapshots_detail.rb
- lib/fog/shared_file_system/openstack/requests/update_snapshot.rb
- spec/fixtures/openstack/shared_file_system/share_snap_crud.yml
- spec/shared_file_system_spec.rb
clean replacement of https://github.com/fog/fog-openstack/pull/208 after renaming to "shared file system"
@gildub fyi
> Manila snapshots

- examples/metric/basics.rb
- gemfiles/Gemfile-1.9
- lib/fog/metric/openstack.rb
- lib/fog/metric/openstack/models/metric.rb
- lib/fog/metric/openstack/models/metrics.rb
- lib/fog/metric/openstack/models/resource.rb
- lib/fog/metric/openstack/models/resources.rb
- lib/fog/metric/openstack/requests/get_metric.rb
- lib/fog/metric/openstack/requests/get_metric_measures.rb
- lib/fog/metric/openstack/requests/get_resource.rb
- lib/fog/metric/openstack/requests/get_resource_metric_measures.rb
- lib/fog/metric/openstack/requests/list_metrics.rb
- lib/fog/metric/openstack/requests/list_resources.rb
- lib/fog/openstack.rb
- test/requests/metric/metric_test.rb
- test/requests/metric/resource_test.rb
This PR adds a basic subset of features of Gnocchi OpenStack service http://gnocchi.xyz/
The Gnocchi service extracted part of Ceilometer functionality related to Metrics. It is a new service in OpenStack catalog.
> Add Gnocchi metric service

- .gitignore
- lib/fog/network/openstack.rb
- lib/fog/network/openstack/requests/create_lbaas_healthmonitor.rb
- lib/fog/network/openstack/requests/create_lbaas_listener.rb
- lib/fog/network/openstack/requests/create_lbaas_loadbalancer.rb
- lib/fog/network/openstack/requests/create_lbaas_pool.rb
- lib/fog/network/openstack/requests/create_lbaas_pool_member.rb
- lib/fog/network/openstack/requests/delete_lbaas_healthmonitor.rb
- lib/fog/network/openstack/requests/delete_lbaas_listener.rb
- lib/fog/network/openstack/requests/delete_lbaas_loadbalancer.rb
- lib/fog/network/openstack/requests/delete_lbaas_pool.rb
- lib/fog/network/openstack/requests/delete_lbaas_pool_member.rb
- lib/fog/network/openstack/requests/get_lbaas_healthmonitor.rb
- lib/fog/network/openstack/requests/get_lbaas_listener.rb
- lib/fog/network/openstack/requests/get_lbaas_loadbalancer.rb
- lib/fog/network/openstack/requests/get_lbaas_pool.rb
- lib/fog/network/openstack/requests/get_lbaas_pool_member.rb
- lib/fog/network/openstack/requests/list_lbaas_healthmonitors.rb
- lib/fog/network/openstack/requests/list_lbaas_listeners.rb
- lib/fog/network/openstack/requests/list_lbaas_loadbalancers.rb
- lib/fog/network/openstack/requests/list_lbaas_pool_members.rb
- lib/fog/network/openstack/requests/list_lbaas_pools.rb
- lib/fog/network/openstack/requests/update_lbaas_healthmonitor.rb
- lib/fog/network/openstack/requests/update_lbaas_listener.rb
- lib/fog/network/openstack/requests/update_lbaas_loadbalancer.rb
- lib/fog/network/openstack/requests/update_lbaas_pool.rb
- lib/fog/network/openstack/requests/update_lbaas_pool_member.rb
All methods implemented along with session persistence for lbaas pools
> Load Balancer: LBaaS v2

- examples/container_infra/basics.rb
- lib/fog/container_infra/openstack/requests/create_bay.rb
- lib/fog/container_infra/openstack/requests/create_cluster.rb
> Usage example for Magnum.

- lib/fog/compute/openstack/models/image.rb
Add size attribute reading OS-EXT-IMG-SIZE:size
> add size to compute image model

- lib/fog/volume/openstack/v1/models/snapshot.rb
- lib/fog/volume/openstack/v2/models/snapshot.rb
> add size attribute to snapshot model

- lib/fog/image/openstack/v1/models/images.rb
- lib/fog/image/openstack/v1/requests/get_image_by_id.rb
- spec/fixtures/openstack/image_v1/images_v1_find_by_id.yml
- spec/image_v1_spec.rb
> Don't rely on #all because responses are paged at 1000 entries.

- lib/fog/openstack.rb
- lib/fog/openstack/core.rb
- lib/fog/shared_file_system/openstack.rb
starting with manila
split off https://github.com/fog/fog-openstack/pull/218
> introduce microversion

- lib/fog/shared_file_system/openstack.rb
- lib/fog/shared_file_system/openstack/models/share.rb
- lib/fog/shared_file_system/openstack/models/share_access_rule.rb
- lib/fog/shared_file_system/openstack/models/share_access_rules.rb
- lib/fog/shared_file_system/openstack/requests/extend_share.rb
- lib/fog/shared_file_system/openstack/requests/grant_share_access.rb
- lib/fog/shared_file_system/openstack/requests/list_share_access_rules.rb
- lib/fog/shared_file_system/openstack/requests/revoke_share_access.rb
- lib/fog/shared_file_system/openstack/requests/share_action.rb
- lib/fog/shared_file_system/openstack/requests/shrink_share.rb
- spec/fixtures/openstack/shared_file_system/common_setup.yml
- spec/fixtures/openstack/shared_file_system/share_actions.yml
- spec/shared_file_system_spec.rb
clean replacement of #212 after renaming to "shared file system"
@gildub fyi
> Manila actions

- lib/fog/shared_file_system/openstack.rb
- lib/fog/shared_file_system/openstack/requests/get_limits.rb
- lib/fog/shared_file_system/openstack/requests/get_quota.rb
- lib/fog/shared_file_system/openstack/requests/update_quota.rb
- test/requests/shared_file_system/quota_tests.rb
> [manila] add quota + limits requests

- lib/fog/compute/openstack.rb
- lib/fog/compute/openstack/models/os_interface.rb
- lib/fog/compute/openstack/models/os_interfaces.rb
- lib/fog/compute/openstack/models/server.rb
- lib/fog/compute/openstack/requests/create_os_interface.rb
- lib/fog/compute/openstack/requests/delete_os_interface.rb
- lib/fog/compute/openstack/requests/get_os_interface.rb
- lib/fog/compute/openstack/requests/list_os_interfaces.rb
> add os_interfaces to compute

- lib/fog/dns/openstack/v2.rb
- lib/fog/dns/openstack/v2/models/zone_transfer_accept.rb
- lib/fog/dns/openstack/v2/models/zone_transfer_accepts.rb
- lib/fog/dns/openstack/v2/models/zone_transfer_request.rb
- lib/fog/dns/openstack/v2/models/zone_transfer_requests.rb
- lib/fog/dns/openstack/v2/requests/create_zone_transfer_accept.rb
- lib/fog/dns/openstack/v2/requests/create_zone_transfer_request.rb
- lib/fog/dns/openstack/v2/requests/delete_zone_transfer_request.rb
- lib/fog/dns/openstack/v2/requests/get_zone_transfer_accept.rb
- lib/fog/dns/openstack/v2/requests/get_zone_transfer_request.rb
- lib/fog/dns/openstack/v2/requests/list_zone_transfer_accepts.rb
- lib/fog/dns/openstack/v2/requests/list_zone_transfer_requests.rb
- lib/fog/dns/openstack/v2/requests/update_zone_transfer_request.rb
> add dns zone transfer

- lib/fog/identity/openstack/v3/requests/list_user_projects.rb
f.i. `domain_id` is a valid option here
> [identity] add options to list user projects

- lib/fog/network/openstack.rb
- lib/fog/network/openstack/requests/create_lbaas_l7policy.rb
- lib/fog/network/openstack/requests/create_lbaas_l7rule.rb
- lib/fog/network/openstack/requests/delete_lbaas_l7policy.rb
- lib/fog/network/openstack/requests/delete_lbaas_l7rule.rb
- lib/fog/network/openstack/requests/get_lbaas_l7policy.rb
- lib/fog/network/openstack/requests/get_lbaas_l7rule.rb
- lib/fog/network/openstack/requests/list_lbaas_l7policies.rb
- lib/fog/network/openstack/requests/list_lbaas_l7rules.rb
- lib/fog/network/openstack/requests/update_lbaas_l7policy.rb
- lib/fog/network/openstack/requests/update_lbaas_l7rule.rb
- lib/fog/network/openstack/requests/update_lbaas_listener.rb
> add lbaas l7 policies and rules

- lib/fog/metric/openstack/requests/list_resources.rb
- test/requests/metric/resource_test.rb
Add an additional request to list only network interface resources.
> List metric resources by network interface type

- lib/fog/compute/openstack/requests/create_server.rb
When I set port_id in nics, it fails to create, if I remove uuid from request, it works.
Also, I need some more parameters in block_device_mappings_v2: 
device_type, disk_bus, guest_format, virtual_name
> Improve create server

- lib/fog/volume/openstack/requests/snapshot_action.rb
- lib/fog/volume/openstack/v2.rb
- lib/fog/volume/openstack/v2/requests/snapshot_action.rb
same like on volumes one can perform certain actions on cinder snapshots
> add snapshot_action to cinder

- lib/fog/openstack/version.rb
> Release 0.1.22

- lib/fog/openstack/version.rb
> Release 0.1.23

- lib/fog/openstack/core.rb
- test/microversion_test.rb
These PR fixes https://github.com/fog/fog-openstack/issues/359
> Test if microversion value not nil and not empty

- lib/fog/compute/openstack/requests/create_key_pair.rb
- lib/fog/compute/openstack/requests/delete_key_pair.rb
Proposed fix for #373 
Change-Id: I028e88e0dfbd8fd7a6b197bda4212b184cc719cc
> Add valid response codes for keypair create/delete.

- .zuul.yaml
reference https://github.com/fog/fog-openstack/issues/385
once this is added we are able to add to OpenLab
configuration to start processing PR payloads
Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>
> Add configuration for OpenLab

- playbooks/fog-openstack-unittest-spec/run.yaml
- playbooks/fog-openstack-unittest-test/run.yaml
Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>
Depends-On: https://github.com/fog/fog-openstack/pull/392
> Add playbooks directory with job definitions

- docs/storage.md
Dear all,
this is a very minor PR that should fix a broken link in docs/storage.md.
Regards
> Docs: fix an anchor link

- README.md
- docs/planning.md
- examples/planning/basics.rb
- fog-openstack.gemspec
- lib/fog/openstack/version.rb
- lib/fog/planning/openstack.rb
- lib/fog/planning/openstack/models/plan.rb
- lib/fog/planning/openstack/models/plans.rb
- lib/fog/planning/openstack/models/role.rb
- lib/fog/planning/openstack/models/roles.rb
- lib/fog/planning/openstack/requests/add_role_to_plan.rb
- lib/fog/planning/openstack/requests/create_plan.rb
- lib/fog/planning/openstack/requests/delete_plan.rb
- lib/fog/planning/openstack/requests/get_plan.rb
- lib/fog/planning/openstack/requests/get_plan_templates.rb
- lib/fog/planning/openstack/requests/list_plans.rb
- lib/fog/planning/openstack/requests/list_roles.rb
- lib/fog/planning/openstack/requests/patch_plan.rb
- lib/fog/planning/openstack/requests/remove_role_from_plan.rb
- test/models/planning/plan_tests.rb
- test/models/planning/plans_tests.rb
- test/models/planning/role_tests.rb
- test/requests/planning/plan_tests.rb
- test/requests/planning/role_tests.rb
Planning module and version were using `Openstack` instead of `OpenStack`
> Replaces Openstack with OpenStack where needed

- playbooks/fog-openstack-unittest-spec/run.yaml
- playbooks/fog-openstack-unittest-test/run.yaml
Jobs are failing due to timeout retrieving keys
> Add additional key servers and keys

- spec/identity_v3_spec.rb
- test/helpers/collection_helper.rb
- test/helpers/model_helper.rb
- test/models/identity/ec2_credentials_tests.rb
- test/models/identity/tenants_tests.rb
- test/models/identity/users_tests.rb
- test/requests/compute/flavor_tests.rb
- test/requests/compute/image_tests.rb
- test/requests/compute/server_tests.rb
- test/requests/network/network_tests.rb
- test/requests/orchestration/stack_files_util_helper_tests.rb
- test/requests/orchestration/stack_files_util_tests.rb
- test/requests/storage/container_tests.rb
- test/requests/storage/large_object_tests.rb
- test/requests/storage/object_tests.rb
Replaces skip with conditional for Fog.mocking check
> Tests: replace skip by conditional for fog-mocking

- lib/fog/identity/openstack.rb
- lib/fog/identity/openstack/v2.rb
- lib/fog/identity/openstack/v3.rb
Addresses https://github.com/fog/fog-openstack/issues/420
> Identity: No path prefix when endpoint is versioned

- lib/fog/openstack/auth/token.rb
- lib/fog/openstack/core.rb
- unit/auth/token_test.rb
Pass along @connections_options to Auth::Token.build
> Auth: Propagate connections options

- lib/fog/identity/openstack.rb
- lib/fog/identity/openstack/v2.rb
- lib/fog/identity/openstack/v3.rb
Backport https://github.com/fog/fog-openstack/pull/447
> [v0.3][Backport] Identity: Fix versionned endpoint

- lib/fog/openstack/auth/token.rb
- lib/fog/openstack/auth/token/v2.rb
- lib/fog/openstack/auth/token/v3.rb
(cherry picked from commit 029bc64fc86e04acd42eaa57c503e117f51aff86)
> Auth: Allow a versionned auth_url path

- lib/fog/openstack/volume/requests/update_volume.rb
- lib/fog/openstack/volume/v1/models/volume.rb
- lib/fog/openstack/volume/v1/requests/update_volume.rb
- lib/fog/openstack/volume/v2/models/volume.rb
- lib/fog/openstack/volume/v2/requests/update_volume.rb
- spec/fixtures/openstack/volume/volume_crud.yml
- spec/fixtures/openstack/volume_v1/volume_crud.yml
- spec/fixtures/openstack/volume_v2/volume_crud.yml
Filtering unsupported params for volume update request should fix this issue https://bugzilla.redhat.com/show_bug.cgi?id=1624840
https://developer.openstack.org/api-ref/block-storage/v3/index.html#update-a-volume
@aufi @gildub
> Filter unsupported params for volume update request

- lib/fog/openstack/core.rb
Backport of https://github.com/fog/fog-openstack/pull/455
> [V0.3][Backport] Use auth_url when catalog is empty

- lib/fog/volume/openstack/requests/update_volume.rb
- lib/fog/volume/openstack/v1/models/volume.rb
- lib/fog/volume/openstack/v1/requests/update_volume.rb
- lib/fog/volume/openstack/v2/models/volume.rb
- lib/fog/volume/openstack/v2/requests/update_volume.rb
- spec/fixtures/openstack/volume/volume_crud.yml
- spec/fixtures/openstack/volume_v1/volume_crud.yml
- spec/fixtures/openstack/volume_v2/volume_crud.yml
Backport of https://github.com/fog/fog-openstack/pull/433
> [backport][v0.3] Filter unsupported params for volume update request

- lib/fog/storage/openstack/requests/copy_object.rb
- lib/fog/storage/openstack/requests/put_object.rb
Backport https://github.com/fog/fog-openstack/pull/457
> [backport][v0.3] Swift: allows 202 for large objects create/update/copy

- lib/fog/compute/openstack/requests/create_flavor.rb
(cherry picked from commit 6685fa58c1cc98562bd3b92158927049fb748907)
>  [backport][v0.1] Don't try to automatically set IDs for new flavors

- lib/fog/openstack/compute/requests/evacuate_server.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1644613
> Nova: filter onSharedStorage for  evacuate_server

- lib/fog/openstack/identity/v3/models/projects.rb
- lib/fog/openstack/identity/v3/requests/get_project.rb
- spec/fixtures/openstack/identity_v3/idv3_project_crud.yml
Get project method failed on bad component(expected absolute path component),
caused by question mark in the path. Updating request to same approach as other
working requests.
> Fix get_project request path

- .travis.yml
- .zuul.yaml
- fog-openstack.gemspec
- playbooks/fog-openstack-unittest-spec/run.yaml
- playbooks/fog-openstack-unittest-test/run.yaml
Backport of https://github.com/fog/fog-openstack/pull/472/files
> [backport][v0.1] - Fix travis and zuul

- lib/fog/compute/openstack/requests/evacuate_server.rb
Backport of https://github.com/fog/fog-openstack/pull/473
> [backport][v0.1] - Fix typo

- lib/fog/compute/openstack/requests/evacuate_server.rb
Backport of https://github.com/fog/fog-openstack/pull/473
> [backport][v0.3] - Fix typo

- lib/fog/openstack/auth/token.rb
> Request JSON from auth server

- docs/workflow.md
current links can be provided.
> docs: intended link DSL REST API v2
