.rubocop.yml, Rakefile, fog-openstack.gemspec
- Added a description for `rake test`
- moved the order of the dependancies
- added rubocop
Now if we decide to use rubocop, running without a `.rubocop.yml` it
comes back with
```
773 files inspected, 12455 offenses detected
```
I suggest we decide on a `.rubocop.yml` before we start doing anything
large with this Gem.
=> Added some testing jobs and descriptions

lib/fog/openstack.rb
Missing requires that were in Fog before
https://github.com/fog/fog/blob/972ae1a990e5ae42a87e3defa85dc3a251818142/lib/fog/openstack.rb
Causing that the classes are not visible
=> Missing OpenStack requires

.travis.yml
Looks like we need this additional step to kick Coveralls off when Travis finishes its test run.
=> Trigger coveralls after Travis finishes

.travis.yml
I can't find any other way to disable build notification emails in Travis.
If anyone wants to receive them, read this and put in a PR: https://docs.travis-ci.com/user/notifications/#Email-notifications
=> Disable email notifications.

lib/fog/openstack.rb, lib/fog/openstack/storage.rb
* Fix 500 due to port presence in Host header for bluemix object storage
* Recognize userid as argument
This is #1 with making port omitting optional.
=> Bluemix object storage fixes

lib/fog/openstack/requests/compute/create_volume.rb
according to http://developer.openstack.org/api-ref-compute-v2.1.html   --> /v2.1/​{tenant_id}​/os-volumes
added `volume_type` and `metadata` in `compute/create_volume` option
=> add volume type and metadata options in create_volume

lib/fog/openstack/docs/metering.md, lib/fog/openstack/models/metering/events.rb
Example usage:
```ruby
query_filter = [{
'field' => 'start_timestamp',
'op'    => 'gt',
'value' => '2016-03-17T09:59:44.606000'
}]
service.events(query_filter)
```
=> Add query filter parameter to metering events

lib/fog/openstack/identity.rb, lib/fog/openstack/identity_v2.rb, lib/fog/openstack/identity_v3.rb, tests/openstack/identity_version_tests.rb
Hello.
If we specify an identity v3 URL as `:openstack_auth_url` parameter in `~/.fog` file, `Fog::Identity::Openstack.new` method returns an instance of identity v2, not v3. It occurs because the configurations has not been read from the file, when `Fog::Identity::Openstack.new` method is invoked. So, `is_v3? args` in the method becomes `false` regardless of URL.
In this modification, identity version is detected after configurations are read from `~/.fog` file.
=> Fix logic to detect identity version

lib/fog/openstack.rb
following discussion on https://gitter.im/fog/fog-openstack
move code to check service existent before it break from getting something from `nil`
=> move code to raise service not found

lib/fog/openstack/requests/compute/get_volume_details.rb
With this modification we can use `wait_for { ready? }` after creating volume when we use mocked data.
=> fix mock volume status when status = 'creating'

lib/fog/openstack/requests/compute/create_server.rb
In Liberty API, sending nil values is not supported anymore.
Fixes for this are being done, but not everywhere. So we should
not send any parameter that was not specified.
=> Do not send blank attributes through API

lib/fog/openstack/models/compute/services.rb, tests/openstack/models/compute/service_tests.rb
OpenStack API currently does not support getting single service by its id.
This feature is wanted in https://github.com/ManageIQ/manageiq/pull/7996 so it seams better to have this ```find``` block here in fog-openstack with a chance to upgrade it to proper request when (and if) OpenStack API supports it.
=> Adds services#get methods with some services tests

lib/fog/openstack/models/compute/server.rb, lib/fog/openstack/requests/compute/evacuate_server.rb
1) don't pass in params with nil values
2) use adminPass instead of admin_password, as that's what the nova API expects
=> A couple fixes for evacuate_server

lib/fog/openstack/models/compute/server.rb, lib/fog/openstack/requests/compute/evacuate_server.rb
Further testing indicated a problem with the recent fixes to evacuate.
Contrary to the OpenStack CLI (where omitting --on-shared-storage is
a 'false' setting), the API treats this as a required param, needing
an explicit true or false.
This PR fixes that, defaulting the param to true
=> Fixing bug in prior evacuate fix for onSharedStorage

fog-openstack.gemspec
This seems to be unused and pulls in nokogiri. Unit tests run smoothly without fog-xml. Getting rid of nokogiri is always a good thing, so here we go.
Please double-check in case the units don't cover essential functionality.
cc @dhague, @Ladas, @seanhandley, @mdarby, @jjasghar
=> Remove fog-xml dependency

lib/fog/openstack/identity.rb, spec/identity_v3_spec.rb, test/openstack/authenticate_tests.rb, tests/openstack/models/identity/ec2_credential_tests.rb, tests/openstack/models/identity/ec2_credentials_tests.rb, tests/openstack/models/identity/role_tests.rb, tests/openstack/models/identity/roles_tests.rb, tests/openstack/models/identity/tenant_tests.rb, tests/openstack/models/identity/tenants_tests.rb, tests/openstack/models/identity/user_tests.rb, tests/openstack/models/identity/users_tests.rb, tests/openstack/requests/identity/ec2_credentials_tests.rb, tests/openstack/requests/identity/helper.rb, tests/openstack/requests/identity/role_tests.rb, tests/openstack/requests/identity/tenant_tests.rb, tests/openstack/requests/identity/user_tests.rb, tests/openstack/requests/image/image_tests.rb
This is step 1 towards identity v3 as the default version.
Effectively since Openstack Kilo, Keystone engine is by default version 3 while
still providing service to API v2.0.
This is one step closer to a configuration where the endpoints for v3 don't have
to be created along the default v2.0 which are not deprecated yet.
=> Identity class creation refactor

lib/fog/openstack/models/network/rbac_policies.rb, lib/fog/openstack/models/network/rbac_policy.rb, lib/fog/openstack/network.rb, lib/fog/openstack/requests/network/create_rbac_policy.rb, lib/fog/openstack/requests/network/delete_rbac_policy.rb, lib/fog/openstack/requests/network/get_rbac_policy.rb, lib/fog/openstack/requests/network/list_rbac_policies.rb, lib/fog/openstack/requests/network/update_rbac_policy.rb, spec/fixtures/openstack/network/common_setup.yml, spec/fixtures/openstack/network/rbacs_crud.yml, spec/network_spec.rb, spec/shared_context.rb
To access identity service for projects in network spec some adjustments to the shared_context was needed. And env `USE_VCR=true` now also works together with the `OS_` env present.
@dhague : FYI
=> implement network rbac policies

lib/fog/openstack/requests/compute/create_server.rb
block_device_mapping_v2 comes under API POST /servers:
http://developer.openstack.org/api-ref-compute-v2.1.html#createServer
This was failing on our Icehouse based installation where the undocumented /os-volumes_boot API is not supported.
=> changed path to use servers.json for block_device_mapping_v2

README.md, supported.md
We need a clear description of which OpenStack projects we support, which versions of the API, our level of compliance (completeness and correctness) and any additional information about the integration itself.
This will eventually be tied in with official OpenStack API compliance tests, details of which are TBD.
=> Add list of supported projects.

test/test_helper.rb
Adds `require` stanza in `test/test_helper.rb` to be able to use
match_schema assertion/expectation
=> Shindo to Minitest - Common part 2

test/authenticate_tests.rb, test/identity_version_tests.rb
Fix test identity leaks causing random errors
When Fog.credentials is altered by a test (or before) it must be restored at the end (or after) of the test.
This fixes authenticate_tests.rb and identity_version_tests.rb accordingly. It now avoids side effects cause some of the random test during testing.
=> Shindo to Minitest - Common part 3

test/helpers/collection_helper.rb, test/helpers/model_helper.rb, test/test_helper.rb
Adds a migrated version of collection_helper.rb & model_helper.rb
helpers to Minitest in /test/helpers
Also, adds a UNIT_TESTS_CLEAN flag to skip broken test
=> Shindo to Minitest: common4

lib/fog/openstack/requests/compute/create_server.rb
Found a bug in create_server which is not detected by Shindo
because of helper method overlap
=> Compute create_server issue with volume

lib/fog/openstack/models/compute/aggregate.rb, lib/fog/openstack/requests/compute/create_aggregate.rb, lib/fog/openstack/requests/compute/update_aggregate.rb
This fixes a few problems with host aggregates:
1) add_host call was succeeding but throwing an exception
2) remove_host call was succeeding but throwing an exception
3) create was not setting the availability_zone attribute
4) update was not working properly
=> various fixes for host aggregate calls

lib/fog/openstack/core.rb, lib/fog/openstack/network.rb, spec/fixtures/openstack/network/common_setup.yml, spec/fixtures/openstack/network/token_expiration.yml, spec/network_spec.rb, spec/shared_context.rb
When I authenticate with auth-token, obviously I cannot get a new token on expiration.
It was nevertheless tried and resulted in the confusing error with status 400: `Expecting to find id or name in user - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.` instead of correctly passing though the 401: `Authentication required` indicating the consumer of the library that a new token needs to be provided.
I will tackle the other services, too.
=> networking token renewal is not possible on token auth

README.md
Add example for downloading image from Glance. Additionally, combine the
image creation from URL and download examples, as both need to use the
upload_data call.
=> Update Glance examples

gemfiles/Gemfile-1.9, lib/fog/openstack/requests/compute/get_limits.rb
with sufficient permissions you can query for `tenant_id` to get the limits of other projects
=> add query to nova limits

lib/fog/openstack/requests/network/update_router.rb
This is an interesting one.
If you set debugging on with the openstack CLI tool and request to clear a router's external gateway then it achieves this by setting the router's `external_gateway_info` to `{}`.
As such, mandating the inclusion of a `network_id` breaks this ability, even if you set the `network_id` to empty string (you get an API validation error).
=> Passing an empty hash clears the external gateway.

lib/fog/openstack/models/orchestration/stack.rb
when using save to create stacks with "template_url", it causes error because default_opotions have a template: null. Heat API takes template over template_url even if it is null. This default options is used for those deprecated methods such as #template=() etc. But for #save(), we do not need the default_options because it prevents us from setting our now option values. @mdarby @geemus @tokengeek @icco @dhague, @Ladas, @seanhandley and @jjasghar Do you guys have time to approve this pull request?
=> remove default_options in #save

lib/fog/openstack/models/orchestration/templates.rb, lib/fog/openstack/orchestration.rb
Fix stck create action, getting not found on template, when
stack has not been created yet. Brought by:
https://github.com/fog/fog-openstack/pull/147
=> Fix stack create action

lib/fog/openstack.rb
Ceilometer failed on getting version from endpoint. Adapted to do not fail.
Error details: http://paste.openstack.org/show/552424/
=> Fix endpoint version lookup

lib/fog/dns/openstack/v2.rb, lib/fog/dns/openstack/v2/models/recordset.rb, lib/fog/dns/openstack/v2/models/recordsets.rb, lib/fog/dns/openstack/v2/models/zone.rb, lib/fog/dns/openstack/v2/models/zones.rb, lib/fog/dns/openstack/v2/requests/delete_recordset.rb, lib/fog/dns/openstack/v2/requests/delete_zone.rb, lib/fog/dns/openstack/v2/requests/get_quota.rb, lib/fog/dns/openstack/v2/requests/get_recordset.rb, lib/fog/dns/openstack/v2/requests/get_zone.rb, lib/fog/dns/openstack/v2/requests/list_recordsets.rb, lib/fog/dns/openstack/v2/requests/list_zones.rb, lib/fog/dns/openstack/v2/requests/update_quota.rb, lib/fog/dns/openstack/v2/requests/update_recordset.rb, lib/fog/dns/openstack/v2/requests/update_zone.rb, spec/dns_v2_spec.rb, spec/fixtures/openstack/dns_v2/common_setup.yml, spec/fixtures/openstack/dns_v2/recordset_crud.yml, spec/fixtures/openstack/dns_v2/zone_crud.yml, spec/shared_context.rb, test/requests/dns_v2/recordset_tests.rb
add header options for admin to query for all_projects or a specific other project
in https://github.com/sapcc/fog-openstack/blob/53b66cb021a6254ea9a69c13dd348d2b6ab0b8b0/lib/fog/dns/openstack/v2/requests/list_recordsets.rb#L7-L17 I would prefer to do the breaking change instead of that deprecation workaround - what do you think? we only offer this DNS API for 4 weeks - most likely it is not consumed, yet or the adaption still fresh to adjust for the change 😄
=> [DNS] add models for zone + recordset incl spec

lib/fog/introspection/openstack.rb
Upstream, the service is registered as "baremetal-introspection"
as the service type name. Setting the service type name manually
produced resulted in an error in set_api_path because it could not
find a supported version.
This patch changes the type from "introspection" to
"baremetal-introspection". It also explicitly sets the api path to
v1 because the version reported by the introspection api is 1.6
which leads Fog::OpenStack.get_supported_version to throw an error.
=> Fix introspection service lookup

lib/fog/openstack.rb
Adds missing require. In some usages, this error occurs:
uninitialized constant Fog::Workflow::OpenStack::V2
=> Fix workflow service lookup

.rubocop.yml
I don't think it is planned to go for ruby 3.0 in the near future
moved out of #205
@gildub FYI
=> disable cop intended for ruby 3.0 migration

lib/fog/orchestration/openstack/models/stack.rb
Hi,
The stack update feature retrieves the current stack template and then merges user's template/ template url to it. However if the user is trying to update with a template url, it gets ignored since the template(self) is always present. 
This change is to consider user's template/template url if it's provided instead of the current stack's template. 
Could you please merge it? Thank you in advance. @Ladas @mdarby
Thanks
Deepali
=> Stack update correction

lib/fog/network/openstack/models/rbac_policy.rb
This ain't necessary and generates a pesky warning:
"lib/fog/core/attributes/default.rb:53: \
warning: redefining `object_id' may cause serious problems"
=> Remove redundant object_id attribute

README.md
This commit fixes incorrect logic for the glance image upload. The
"upload_data" method was incorrectly accessed from the glance object,
and not the handle to the created image.
=> Fix glance image upload example

lib/fog/openstack/version.rb
Need to do a release to 0.1.18 once this is merged.
Completes #228
=> Deprecation warning for Ruby 1.9.

examples/container_infra/basics.rb, lib/fog/container_infra/openstack/requests/list_bay_models.rb, lib/fog/container_infra/openstack/requests/list_bays.rb, lib/fog/container_infra/openstack/requests/list_cluster_templates.rb, lib/fog/container_infra/openstack/requests/list_clusters.rb
Without this, a lot of the model attributes are `nil`.
=> Show details for Magnum list functions.

lib/fog/image/openstack/v2/models/images.rb, spec/fixtures/openstack/image_v2/images_v2_find_by_id.yml, spec/image_v1_spec.rb, spec/image_v2_spec.rb
This is consistent with the behavior of `get` in other
models, e.g. servers, volumes.
Signed-off-by: Beyhan Veli <beyhan.veli@sap.com>
=> Handle NotFound in images v2 model's `get`

lib/fog/compute/openstack/requests/update_quota.rb, lib/fog/volume/openstack/requests/update_quota.rb
In both the Compute and Volume update_quota actions, update_quota
was adding tenant_id to the quota_set hash. It doesn't belong there.
tenant_id is already in the URL and it doesn't go into the quota
hash. For the Compute operation, adding it to quota_set causes it
to fail. For Volume, it doesn't fail, but it still doesn't belong there.
=> removed extraneous tenant_id from quota_set in update_quota

gemfiles/Gemfile-1.9
fix failing test for ruby 1.9: nokogiri 1.7.0 was released yesterday and dropped ruby < 2 support (https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#backwards-incompatibilities)
=> pin down nokogiri gem for ruby 1.9

lib/fog/dns/openstack/v2/requests/create_zone.rb
attributes is a valid zone create parameter, see [designate source](https://github.com/openstack/designate/blob/master/designate/objects/adapters/api_v2/zone.py#L46) or [designate backend docu](http://docs.openstack.org/developer/designate/pools/scheduler.html#attribute-filter)
=> [dns] add immutable zone attribute 'attributes'

examples/event/basics.rb, lib/fog/event/openstack.rb, lib/fog/event/openstack/models/event.rb, lib/fog/event/openstack/models/events.rb, lib/fog/event/openstack/requests/get_event.rb, lib/fog/event/openstack/requests/list_events.rb, lib/fog/openstack.rb, test/requests/event/event_tests.rb
Events loading from Ceilometer service will be moved to separated service
called Panko from Ocata Openstack release. Panko has own entry in Openstack
endpoint list with an "Event" service type.
Adding support for this service extracting its code from Metering.
https://github.com/openstack/panko
=> Add Panko Event service

lib/fog/identity/openstack/v3/models/domains.rb, spec/fixtures/openstack/identity_v3/idv3_domain.yml
Applies a fix that was previously added to the
`Fog::Identity::OpenStack::V3::Projects` class in this commit:
https://github.com/fog/fog-openstack/pull/85/files#diff-598cf6b1198a78b938b1358eba6392e8
Fixes GH issue: #56
=> Make caching for keystone V3 domains optional and configurable

lib/fog/openstack.rb
It may happen that identityv3 endpoint is not present in the catalog (but only v2 for local users) and public users have to connect to v3 endpoint, which is "often" the auth url - so try it
=> Allow to connect to identity_v3 endpoint even if it's not in the catalog

lib/fog/volume/openstack/requests/update_metadata.rb
Huawei FusionSphere OpenStack return a 202 HTTP code when updating volume metadata
Fix #284
=> Update metadata update expected return code

lib/fog/image/openstack/v1/models/images.rb, lib/fog/image/openstack/v1/requests/get_image_by_id.rb, spec/fixtures/openstack/image_v1/images_v1_find_by_id.yml, spec/image_v1_spec.rb
This patch fixes the logic when finding an image by ID, using the V1
version of Glance API. Response from Glance when getting details of
an image contains headers prefixed by one of two strings:
- X-Image-Meta-
- X-Image-Meta-Property
The second one is used for enumerating all the custom properties
associated with given image and the current version of the code wasn't
correctly handling them.
The source of the bug was that because `X-Image-Meta-` was used as the
prefix when selecting headers, all the custom properties were selected
as well - and then incorrectly treated like normal properties for that
image.
=> Extract custom properties when searching for images

lib/fog/compute/openstack/requests/delete_server.rb
This patch modifies the logic in the mock implementation of deleting a server.
The original code has nil checks for making sure that we will only remove a
server from a group if that group exists - but it does not check whether the
whole collection of groups exist.
This can lead to a situation that if the user data when mocking doesn't contain
the key `data[:server_groups]`, we'd be hitting the nil pointer exception on the
calls to
data[:server_groups].find
This only affects the mock implementation.
=> Handle nil values of data[:server_groups] in mock delete_server

lib/fog/compute/openstack/requests/create_server.rb
This patch removes two lines of unnecessary code - it looks like the exact same
calls are done two few lines above (lines 156 - 157).
=> Remove some dead code from mocks

lib/fog/metering/openstack/requests/get_samples.rb
The Liberty release of Ceilometer introduced the idea of a limit variable to tell the API how many results you want. By default this is set to 100 in the server config. The onus is on the client to select how many results it wants.
I propose we default to a very high number as this will provide minimal disturbance to users.
Read this: https://specs.openstack.org/openstack/ceilometer-specs/specs/liberty/mandatory-limit.html
and this: https://docs.openstack.org/developer/ceilometer/webapi/v2.html#get--v2-meters-(meter_name)
=> Allow more than 100 results post-Liberty.

lib/fog/storage/openstack.rb, lib/fog/storage/openstack/models/file.rb, lib/fog/storage/openstack/requests/post_object.rb, test/requests/storage/object_tests.rb
When an object is saved, fog should attempt to issue a POST, as
opposed to always reuploading the object. The patch adds a @dirty
instance variable to the File model to keep track of whether the
object needs to be PUT or if a POST should be issues. To support the
model, a post_object request is also added. The expected return code
is 202.
Fixes: #289
=> Swift: support POST for objects.

test/requests/storage/container_tests.rb, test/requests/storage/large_object_tests.rb, test/requests/storage/object_tests.rb, test/test_helper.rb
Fixes for the existing storage tests to pass against a Swift cluster. Tested all of the methods, except for the temp URL, as I did not have it configured on the cluster. Will address the tempurl failures in a subsequent patch.
=> Swift: Fix existing requests storage tests to work live.

lib/fog/storage/openstack/requests/get_object_https_url.rb, test/requests/storage/object_tests.rb
As described in https://github.com/fog/fog-core/issues/210
there numeric options are converted to integers in fog-core.
This crashes when HMAC tries to sign, which requires the
value to be a string. This changes ensures, that is acutally
a string.
Added a unit test to validate the fix.
Closes fog/fog-core#210
Signed-off-by: Tom Kiemes <tom.kiemes@sap.com>
=> Handle numeric temp url keys

.travis.yml
all gates to work
Ruby 2.2.0 requires a bundler update to work.
updates bundler in .travis.yml to fix the gate
The update may or may not be welcome. In that case, the 2.2.0 gate should be in the `Allowed Failures`
=> Ruby 2.2.0 has an old bundler version:

lib/fog/orchestration/openstack/requests/update_stack.rb
Use the same name for create_stack and update_stack variables. 
This helps C&P while adding feature to both those functions (see #317 )
=> #322 Conform variable names to create_stack and signature.

.travis.yml
ManageIQ and other projects .travis.yml are tested
against ruby 3.4.x and 3.2.x. Moreover ruby 2.1
support has ended.
=> Fixes: #335. Add ruby 3.4.1 and 3.2.1. Remove ruby 2.1.x.

lib/fog/openstack.rb, lib/fog/orchestration/openstack/models/stack.rb, lib/fog/orchestration/openstack/requests/create_stack.rb, lib/fog/orchestration/openstack/requests/update_stack.rb, lib/fog/orchestration/util/recursive_hot_file_loader.rb, test/requests/orchestration/foo.sh, test/requests/orchestration/hot_1.yaml, test/requests/orchestration/hot_2.yaml, test/requests/orchestration/local.yaml, test/requests/orchestration/local_fullpath.yaml, test/requests/orchestration/no_recursion.yaml, test/requests/orchestration/simple.yaml, test/requests/orchestration/stack_files_util_helper_tests.rb, test/requests/orchestration/stack_files_util_tests.rb, test/requests/orchestration/stack_files_util_tests.yaml, test/requests/orchestration/stack_tests.rb, test/requests/orchestration/template.yaml, test/test_helper.rb
Resolve files in yaml template. 
get_file specs are here https://docs.openstack.org/heat/pike/template_guide/hot_spec.html#get-file
=> 313 heat files parameter

fog-openstack.gemspec
It seems zip is not used by fog-openstack, removing.
=> [WIP] Remove rubyzip dependency

lib/fog/compute/openstack.rb, lib/fog/compute/openstack/models/server_group.rb, test/models/compute/server_group_tests.rb
OpenStack Mitaka adds support for soft (anti) affinity. For this the compute API mircoversion 2.15 is required. Older installation of OpenStack and older API microversions will result in a 400
http error code.
- We introduced Microversions to the compute service in order to support soft (anti) affinity.
- We added the soft affinity policies for server groups.
- We explicitly request either the v2 or v2.1 API endpoint version of the compute service.
Note: This PR is a follow up of https://github.com/fog/fog-openstack/pull/339
=> Introduce microversions to compute service

fog-openstack.gemspec
Upgrading to fog-core 2.0 breaks the OpenStack::Metadata class and at
least two tests. Pin the dependency to be < 2.0 until those issues are
resolved.
=> Do not upgrade to fog-core 2.0.

lib/fog/compute/openstack.rb
Some OpenStack systems provide URLs like
http://host:port/v2.1 for the compute service which didn't match.
This fix changes the version regex to match such URLs
=> Allow compute URLs ending with service version

.rubocop.yml
Set 150 as a reasonable max class length in .rubocop.yml (which is a nice pick for new code). Old code may need refactoring to achieve that goal.
Feedback welcome for the right pick. Running rubocop on the project we get: 
```
lib/fog/compute/openstack/models/server.rb:7:7: R: Class has too many lines. [309/100]
lib/fog/dns/openstack/v2.rb:78:9: R: Class has too many lines. [218/100]
lib/fog/compute/openstack.rb:5:5: R: Class has too many lines. [188/100]
lib/fog/image/openstack/v2/models/image.rb:7:9: R: Class has too many lines. [163/100]
lib/fog/network/openstack.rb:5:5: R: Class has too many lines. [187/100]
lib/fog/network/openstack.rb:264:7: R: Class has too many lines. [171/100]
lib/fog/baremetal/openstack.rb:86:7: R: Class has too many lines. [150/100] …
```
=> 150 lines is a suitable class length.

lib/fog/storage/openstack.rb
This adds the fixes found in
https://github.com/fog/fog-aws/commit/13bda13933711c7d3efa00bcf1e913e053aa34e6
that come up due to changing some gem dependencies around.
See https://github.com/fog/fog-core/issues/171 and
https://github.com/fog/fog-core/pull/170
Without this, trying to use "put_object" for storage results in:
```
NameError: uninitialized constant Fog::Storage::MIME
```
=> Fix MIME issues

test/requests/orchestration/stack_tests.rb
Fixed deprecation warnings in stack_tests.
As  @stacks variable defined here
https://github.com/fog/fog-openstack/compare/master...ioggstream:320-fix-deprecation?expand=1#diff-47b26349d7f38ae7fcd7ef799c7d2f0eL47 
is a boolean, I created a new Stack instance.
=> #320 fix deprecation warnings in stack_tests

README.md
If the rake gem is missing when the dependency installation procedure is triggered by running `/bin/setup`, it exits with the following error:
```
Building native extensions.  This could take a while...
ERROR:  Error installing rainbow:
ERROR: Failed to build gem native extension.
current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 mkrf_conf.rb
current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError) …
```
=> Reformat setup instructions for development

.rubocop.yml
Test blocks to be longer that 25 lines, and generally longer than actual blocks.
Excludes test methods from BlockLength check.
=> Exclude test methods from BlockLength check

lib/fog/orchestration/util/recursive_hot_file_loader.rb, test/requests/orchestration/local_fullpath.yaml, test/requests/orchestration/no_recursion.yaml
Test are broken by the absolute path introduced since https://github.com/fog/fog-openstack/commit/2b32ce8b3d000b20d196601ddbda048d9a463554.
Initially the affected tests failure seemed to be local only but others forks are being impacted too. Therefore the urgent merge.
=> Broken Orchestration tests: Use relative path

README.md, docker-compose.yml
Provide a docker-compose.yml file enabling developing and
testing in a brand new ruby container, thus mimicking
travis behavior. Modifying the docker-compose enables
testing on different ruby versions too.
=> Fixes #353: run tests in a travis-like docker container.

.travis.yml, lib/fog/orchestration/util/recursive_hot_file_loader.rb, test/requests/orchestration/local_fullpath.yaml, test/requests/orchestration/no_recursion.yaml, test/requests/orchestration/stack_files_util_tests.rb
There is no reasonable way to run tests that use resources with a
hardcoded assumption about where the resource resides. Skip these
tests, unless the directory structure is setup for them to run
successfully (should be the case on Travis and in a docker container).
=> Skip tests that make assumptions about the FS.

lib/fog/storage/openstack.rb, lib/fog/storage/openstack/requests/public_url.rb, lib/fog/storage/openstack/requests/put_object.rb, test/requests/storage/object_tests.rb
Fixing up a prior PR (https://github.com/fog/fog-openstack/pull/341) that added these mocks.
=> Mocks for put_object and public_url

lib/fog/identity/openstack.rb, lib/fog/identity/openstack/v2.rb, lib/fog/identity/openstack/v3.rb, lib/fog/network/openstack.rb, test/test_helper.rb
Restores the built-in Mock feature which was killed by Mock classes being moved to `/test/lib/` in https://github.com/fog/fog-openstack/pull/223.
For this to eventually happen a broader work is necessary, this is being discussed [here](https://github.com/fog/fog-core/issues/198)
=> Reverting Mock removal

lib/fog/storage/openstack/models/file.rb
Code at https://github.com/fog/fog-openstack/blob/master/lib/fog/storage/openstack/models/files.rb#L58-L59 can return nil, adapting _body_ method to not fail in this case.
=> Fix error on empty body of File

lib/fog/compute/openstack/models/server.rb
for not created host id is not exists, but possibility to assign sec.groups should be.
this patch allow return all groups if host not created yet
https://github.com/theforeman/foreman/pull/5103
=> Fix for https://github.com/theforeman/foreman/pull/5103

lib/fog/compute/openstack/requests/get_server_volumes.rb
Remove redundant slash in **get_server_volumes.rb** file. For ISSUE: #389
=> Remove redundant slash

lib/fog/storage/openstack/models/file.rb, test/models/storage/file_tests.rb
This PR adds ability to set cache-control header while uploading a file.
=> Storage: Set cache-control header for a file

Rakefile
Removes double definitions of tests.
Default now launch both tests
=> Rake: reduce double definition; Default launch

lib/fog/dns/openstack.rb, lib/fog/identity/openstack.rb, lib/fog/image/openstack.rb, lib/fog/openstack.rb, lib/fog/volume/openstack.rb
Per the idea of https://github.com/fog/fog-openstack/pull/386 this allows service class versions to be autoloaded so they can be reopened properly.
=> Moves autoload to allow reopening

lib/fog/compute/openstack.rb, lib/fog/compute/openstack/requests/get_vnc_console.rb, lib/fog/compute/openstack/requests/remote_consoles.rb
Addresses https://github.com/fog/fog-openstack/issues/400
Also makes sure get_vnc_console runs only if microversion is < '2.5'
https://bugzilla.redhat.com/show_bug.cgi?id=1596320
When Nova is queried with Microversion < 2.6:
```bash
curl http://192.0.2.6:8774/v2.1/servers/f01dbe57-b811-423e-92a8-e1b77610129b/action -H "X-Auth-Token: $TOK" -H "Content-Type: application/json" -H "X-OpenStack-Nova-API-Version: 2.5" -X POST -d '{"os-getVNCConsole": {"type": "novnc"}}'
```
The request performs:
```bash     
{"console": {"url": "http://192.0.2.6:6080/vnc_auto.html?token=6a91cf7a-6fdc-44f0-80dc-19e0ff5131b9", "type": "novnc"}}
```
When using a Microversion > 2.5:
```bash
$ curl http://192.0.2.6:8774/v2.1/servers/f01dbe57-b811-423e-92a8-e1b77610129b/action -H "X-Auth-Token: $TOK" -H …
```
=> Compute: Add remote console

lib/fog/compute/openstack/models/key_pair.rb, lib/fog/compute/openstack/requests/create_key_pair.rb, lib/fog/compute/openstack/requests/delete_key_pair.rb
Added `user_id` to `create` and `delete` methods for keypairs in order to create/delete keypairs with assigned user ids to them. 
This needed for further fixes in https://bugzilla.redhat.com/show_bug.cgi?id=1589766
=> Assign userid to keypairs

lib/fog/compute/openstack/requests/create_flavor.rb
The ID field is optional when creating new flavors in Openstack. If the field is left empty, Openstack will provide a UUID automatically. It's unnecessary for Fog to automatically try to guess the ID, and the ID-guessing code results in strange behavior if a flavor was created outside Fog with a non-integer ID.
https://bugzilla.redhat.com/show_bug.cgi?id=1608230
=> Don't try to automatically set IDs for new flavors

lib/fog/identity/openstack.rb
This is just a first step before using :api_version parameter to be added to allow to use Identity v2 without guessing on the auth_url path or such.
This should help with case like https://github.com/fog/fog-openstack/pull/361
=> Simple identity v3 by default

.gitignore
Ignores 'test/lorem.txt' file which is left behind when test are interrupted.
=> gitignore test/lorem.txt

.rubocop.yml, lib/fog/identity/openstack.rb
This offers backward compatibility as before the new boostrapping approach.
A deprecation message is added in such case.
=> Allows openstack_auth_url to use version

lib/fog/image/openstack/v2/models/image.rb, spec/fixtures/openstack/image_v2/image_v2_reload.yml, spec/image_v2_spec.rb
Another step closer to support fog-core 2+
https://github.com/fog/fog-openstack/issues/349
https://github.com/fog/fog-core/issues/236
=> Image: Avoid using dynamic attribute

lib/fog/storage/openstack.rb, lib/fog/storage/openstack/requests/get_object_https_url.rb, lib/fog/storage/openstack/requests/public_url.rb
Uses @openstack_management_uri for scheme, host and port which allow to avoid dedicated instance variables.
Adjusts Mock accordingly.
=> Storage: Use @openstack_management_uri only

lib/fog/openstack/auth/token/v2.rb
OVH has numeric tenantName and expects it to be a string. Unfortunately fog converts any number string into number. This result in error when trying to autenticate:
```
Expected([200, 201]) <=> Actual(400 Bad Request)
excon.error.response
:body          => "{\"error\": {\"message\": \"object of type 'int' has no len()\", \"code\": 400, \"title\": \"Bad Request\"}}"
:cookies       => [
]
:headers       => {
"Content-Length"         => "96"
"Content-Type"           => "application/json"
"Vary"                   => "X-Auth-Token"
"X-IPLB-Instance"        => "24498"
"x-openstack-request-id" => "req-b8c0abe4-72e7-4811-b977-7700002c2990"
}
:host          => "auth.cloud.ovh.net"
:local_address => "192.168.0.14"
:local_port    => 44356
:path          => "/v2.0/tokens"
:port          => 443 …
```
=> Fix for OVH v2.0 auth with numeric tenant

lib/fog/baremetal/openstack.rb, lib/fog/introspection/openstack.rb, lib/fog/nfv/openstack.rb
For baremetal, introspection and nvf
This is in the continuity of the new bootstrapping approach (v0.2+)
=> openstack_identity_api_version missing

lib/fog/openstack/auth/token/v2.rb
servers.com OpenStack implementation expects `username` to be a string. Unfortunately fog converts any number string into number.
=> Fix for servers.com v2.0 auth

lib/fog/openstack/auth/token.rb, lib/fog/openstack/auth/token/v2.rb
Allows for unscoped token under Keystone v2.0
=> Identity v2: unscoped token fix

fog-openstack.gemspec, lib/fog/network/openstack/models/network.rb
Image Rspec: Avoid using dynamic attribute
=> Network model: remove subnet attribute to support fog-core 2+

fog-openstack.gemspec, lib/fog/openstack.rb
Fog-core 2.1.1 implies a entire namespace change which is available from fog-core 1.0.0.
So we want to make sure that fog-core version dependency is less than 2.1.0 but at same time we backport https://github.com/fog/fog-core/commit/06b7ab4 through a monkey patch to ensure not breaking behaviour if fog-core 2+ but less than 2.1.1 is used.
=> Fog-core dependency: less than 2.1.1 along with monkey patch

lib/fog/openstack/image/v1.rb, lib/fog/openstack/image/v2.rb, spec/fixtures/openstack/image_v1/common_setup.yml
Image service type v1 and v2 need to be differentiated.
Since openstack service type [1] doesn't offer an alias to distinguish between image v1 and v2 and because v1 is depreciate, let's keep the "image" service type to v2 and assign "imagev1" to v1.
While at it, let's also adds "imagev2" as a possible service type for v2.
https://github.com/fog/fog-openstack/issues/438
[1] https://git.openstack.org/cgit/openstack/service-types-authority/
=> Image::V1: Service type is now imagev1

lib/fog/openstack/identity/identity.rb, lib/fog/openstack/identity/v2.rb, lib/fog/openstack/identity/v3.rb
The endpoint (from the catalog) must be used and not the auth_url must be used to check for a version in the path.
=> Identity: Fix versionned endpoint

lib/fog/openstack/auth/token.rb, lib/fog/openstack/auth/token/v2.rb, lib/fog/openstack/auth/token/v3.rb
The prefix_path allows to ignore version  ('/v3' or 'v2.0') when the identity endpoint (`auth_url`)
contains a version in its path.
=> Auth: Allows an auth_url path to contain version

lib/fog/openstack/core.rb
Avoids trying to get endpoint url when Catalog is empty, for instance when the tenant/project is not provided (unscoped token).
=> Token: Use auth_url when catalog is empty

lib/fog/openstack/storage/requests/copy_object.rb, lib/fog/openstack/storage/requests/put_object.rb
Adds HTTP return code '202' (Accepted) for Container PUT and COPY requests.
OpenStack object storage API reference guide [1] implicitly mentions return code '202' is expected when dealing with large object for creation, update or copy [2]. 
[1] https://developer.openstack.org/api-ref/object-store/?expanded=copy-object-detail,create-or-replace-object-detail#create-or-update-object-metadata
[2] https://docs.openstack.org/swift/latest/api/large_objects.html
Thanks to @NickLaMuro for reporting this issue.
=> Swift: Allow 202 for large objects creation/update/copy

lib/fog/compute/openstack/requests/evacuate_server.rb
(cherry picked from commit df5b448433cb12b43962c76acc51e7bc36d0f742)
=> [backport][v0.1] - Nova: filter onSharedStorage for evacuate_server

.rubocop.yml
This should help to prevent binding.pry in production.
=> Add debugger warning

test/requests/workflow/workflow_tests.rb, test/volume_tests.rb
A couple of tests are failing after #468 because a couple of paths were left unchanged for volume and workflow.
=> Fix a couple of paths to clear tests

lib/fog/openstack/volume/requests/create_volume.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1660896
@gildub What if anything do I need to do here to support older versions of Cinder that don't know about this parameter?
https://docs.openstack.org/cinder/latest/admin/blockstorage-volume-multiattach.html
=> Add multiattach parameter to volume creation

lib/fog/openstack/storage/requests/get_object_https_url.rb
Allow to set filename for downloaded file.
Basically 
becomes
=> Allow custom filename through Content-Disposition header

lib/fog/openstack/core.rb
It seems when using fog-openstack-1.x with Chef [1] , @openstack_endpoint_type
becomes a frozen string and fails with FrozenError. Unfortunately, I haven't
been able to reproduce this issue in unit tests but I know for a fact that this
fixes the issue. Looking through the code base, this is the only place where a
``gsub!`` is used in this manner.
Further debugging shows this stack trace which lead me to this:
```
DEBUG: FrozenError: openstack_role[service] (openstack-identity::registration line 70) had an error: FrozenError: can't modify frozen String
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/fog-openstack-1.0.8/lib/fog/openstack/core.rb:200:in `gsub!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/fog-openstack-1.0.8/lib/fog/openstack/core.rb:200:in `setup' …
```
=> Fix potential issue with frozen strings with openstack_endpoint_type

fog-openstack.gemspec
Bundler ~> 1 dependency failed on certain Ruby version. Removing version requirement.
=> Remove bundler pessimistic 1 version

lib/fog/openstack/core.rb
When OpenStack User's password was a Number, fog-core coerced it to Numeric type, which caused
HTTP 400 failure leading to print request malformed error message including the password.
Value's coercing function from fog-core is a feature and it should not be changed propably,
so adding String cast directly to OpenStack provider.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1723180
=> Ensure User's Password is always String

lib/fog/openstack/orchestration.rb, lib/fog/openstack/orchestration/models/stacks.rb, lib/fog/openstack/orchestration/requests/show_stack.rb
If searching in all Stacks including nested ones is needed, it is necessary
use find Stack by ID as the only argument.
Heat API supports this call [1]. Updating current find_by_id method to
use this API call and making it not-deprecated.
Related to https://github.com/ManageIQ/manageiq-providers-openstack/pull/487
[1] https://docs.openstack.org/api-ref/orchestration/v1/?expanded=find-stack-detail,show-stack-details-detail#find-stack
=> Update Orchestration Stack find by ID method

lib/fog/openstack/core.rb
This PR fixes #507 and potentially #501 and #502 
Since f72d2fc (first released in v0.1.20) fog-openstack mutates the
params passed on `Fog::Openstack::Core#request` by calling
`#delete(:headers)`[1] on the params hash to access it.
In case of a re-authentication the request is re-issued[2] but the
headers hash is no longer present. As a result all headers passed by the
user are lost and the request gets just the default headers[3].
This commit fixes the aforementioned behavior by not mutating the params
hash in order to access its `:headers` part.
[1]: https://github.com/fog/fog-openstack/blob/v1.0.10/lib/fog/openstack/core.rb#L57
[2]: https://github.com/fog/fog-openstack/blob/v1.0.10/lib/fog/openstack/core.rb#L61
[3]: https://github.com/fog/fog-openstack/blob/v1.0.10/lib/fog/openstack/co …
=> openstack::core: Don't mutate params between request retries

fog-openstack.gemspec
In 118a99282e1225db8735f5547280788ede97a09e this was added, but I can't find any place that it would be used.
=> Remove ipaddress dependency

lib/fog/openstack/orchestration/util/recursive_hot_file_loader.rb, test/requests/compute/address_tests.rb
- **fix minitest after tests call to newer, non-deprecated style**
- **update/fix yaml safe load arguments in recursive hot file loader**
=> start fixing main tests

lib/fog/openstack/auth/token/v3.rb, lib/fog/openstack/compute.rb, lib/fog/openstack/core.rb, lib/fog/openstack/identity/v3.rb, lib/fog/openstack/network.rb, spec/fixtures/openstack/identity_v3/authv3_application_credential.yml, spec/identity_v3_spec.rb, spec/shared_context.rb
I've used this code for using application credentials for authentication in Openstack. I think it would be valuable if this could be added in the fog-openstack project.
This will fix issue #510
This can be used as alternative next to it's original credentials options. To use application credentials I've set the following parameters:
```
compute_client = Fog::Compute.new  :openstack_auth_url => ENV['OS_AUTH_UR'],
:openstack_application_credential_secret => ENV['OS_APPLICATION_CREDENTIAL_SECRET'],
:openstack_application_credential_id => ENV['OS_APPLICATION_CREDENTIAL_ID']
```
CC @dhague (sorry if I should cc another member)
=> Add support for using application credentials for authentication

lib/fog/openstack/storage.rb
* Swift supports application credentials: https://github.com/restic/restic/pull/2156
* see also https://github.com/fog/fog-openstack/pull/533
=> Add application_credential params to Storage class
